---
- name: Deprovision VMs from Proxmox and NetBox
  hosts: proxmox
  gather_facts: false
  roles:
    - role: proxmox_deprovision
      proxmox_config: "{{ proxmox | default({}) }}"
      vms_to_delete: "{{ vms_to_delete }}"
