---
# roles/proxmox_deprovision/defaults/main.yml

proxmox_defaults:
  node: pve01.lab.example.com
  timeout: 300
  snippets_dir: /var/lib/vz/snippets

proxmox_config: {}

netbox:
  api_url: ""
  token: ""
  ssl_verify: true

technitium_dns:
  enabled: false
  api_url: ""
  api_port: 5380
  api_token: ""
  validate_certs: true
  zone: ""

netbox_cleanup: true
vms_to_delete: []
